### ISSUE TITLE
经常出现的一个错误

### ISSUE THREAD

**Issue by 4snows** [angcyo/PLDroidDemo#1]
我在应用audiovideorecordingdemo这个项目的时候经常遇到MediaMuxer停止错误的提示。log如下：
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture W/System.err: **java.lang.IllegalStateException: Can't stop due to wrong state.**
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture W/System.err:     at android.media.MediaMuxer.stop(MediaMuxer.java:228)
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture W/System.err:     at com.test.android.videocapture.slvideocapture.rencoder.MediaMuxerRunnable.stopMediaMuxer(MediaMuxerRunnable.java:122)
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture W/System.err:     at com.test.android.videocapture.slvideocapture.rencoder.MediaMuxerRunnable.run(MediaMuxerRunnable.java:316)
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture D/MPEG4Writer: Audio track stopping
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture E/MPEG4Writer: **Stop() called but track is not started**
05-11 09:29:17.839 31809-32730/com.test.android.videocapture.slvideocapture E/angcyo-->: 混合器退出...

退出重新开启应用就没问题了。这个问题可能是什么原因呢？我猜测是某个track没有添加进去，但是按照这个逻辑，只有添加成功后才能开启muxer。希望能有解答

**Comment by peakfa** [comment]
最近正在搞这个问题逻辑问题在addtrace 的时候状态判断有误，参考：https://getpocket.com/a/read/1491672190   
可以留个联系方式吗？2937454020
